# Conclusion

The overall goal of this project was to investigate the prevalence and impact of post-COVID symptoms over the past year and a half. Through our analysis, we showed that even though the number of people affected by Long COVID has been steadily decreasing since June 2022, many people are still not only affected by Long COVID (~10% of those that have ever had COVID, and ~6% of all adults), but have lasting detrimental health conditions as a function of Long COVID (~80% of adults that have ever had Long COVID, and ~6% of all adults). Additionally, we showed that certain demographics are more likely than others to develop post-COVID-symptoms, namely people that identify as either transgender or female, people with less than a high school diploma, people with disabilities, and people from certain states in the U.S. South or Midwest (West Virginia, Alabama, Mississippi, and Oklaholma). While these findings are definite successes, especially considering our initial research questions outlined in the project introduction, our analyses did also reveal several limitations with the study design and survey responses. For one, the data repository for the project did not contain any information on the intersection between different subgroups, limiting our analyses to only look at one subgroup at a time. Our analyses also showed decreasing trends in the cumulative number of Long COVID-cases, which should not be possible if the sample surveyed was a representative sample of the U.S. adult population. In the future, these problems could both be reduced by bolstering the survey design to not only store increased information on the survey responses, namely on the intersection-size between subgroups, but also to survey more people from as many locations as possible in order to get the best representative sample possible.
